#ifndef BITCOIN_CONFIG_H
#define BITCOIN_CONFIG_H

#define CLIENT_VERSION_MAJOR 1
#define CLIENT_VERSION_MINOR 1
#define CLIENT_VERSION_REVISION 1
#define CLIENT_VERSION_BUILD 1
#define CLIENT_VERSION_IS_RELEASE 1
#define COPYRIGHT_YEAR 1

#endif
